---

- hosts: all
  gather_facts: false
  become: yes
  roles:
    - repos
  tags: tested 

- hosts: frontends
  gather_facts: false
  become: yes
  roles:
    - haproxy


- hosts: apps
  gather_facts: false
  become: yes
  roles:
    - tomcat
    - apache
  uri: url=http://localhost

- hosts: appdbs
  gather_facts: false
  become: yes
  roles:
    - postgresql


