---

- name: Dynamic inventory from OSP
  hosts: jumpbox
  gather_facts: false

  tasks:
    - name: Fetch Instance Info
      tags: dynamic_inventory
      os_server_facts:
        cloud: ospcloud
        region_name: RegionOne
      register: result


    - name: Add host to metadata group
      tags: dynamic_inventory
      add_host:
        name: "{{ item.public_v4 }}"
        group: "{{ item.metadata.group }}"
      with_items: "{{result.ansible_facts.openstack_servers}}"

    - name: Add host to deployment name group
      tags: dynamic_inventory
      add_host:
        name: "{{ item.public_v4 }}"
        group: "{{ item.metadata.deployment_name }}"
      with_items: "{{result.ansible_facts.openstack_servers}}"


    - name: Configure yum repositories on all servers
      hosts: all
      gather_facts: false
      become: yes
      roles:
          - repos
      tags: tested 

    - name: Configure frontend with HAproxy
      hosts: frontends
      gather_facts: false
      become: yes
      roles:
        - haproxy
      tags: tested     

    - name: Configure yum repositories on all servers
      hosts: apps
      gather_facts: false
      become: yes
      roles:
        - tomcat
        - apache
      tags: tested 

    - hosts: appdbs
      gather_facts: false
      become: yes
      roles:
        - postgresql
      tags: tested 



