---

- hosts: jumpbox
  gather_facts: true
  become: yes
  roles:
    - dynamicip
  


- hosts: all
  gather_facts: false
  become: yes
  roles:
    - repos
  tags: tested 

- hosts: frontends
  gather_facts: false
  become: yes
  roles:
    - haproxy
  tags: tested     


- hosts: apps
  gather_facts: false
  become: yes
  roles:
    - tomcat
    - apache
  tags: tested 

- hosts: appdbs
  gather_facts: false
  become: yes
  roles:
    - postgresql
  tags: tested 

#- name: test URL
#  hosts: frontends
#  gather_facts: false
#  become: true
#  tasks:
#  - uri:
#      url: http://localhost
#      return_content: yes

