- name: Delete the 3-tier instances on OSP
  hosts: jumpbox
  gather_facts: false
  vars_files:
    - ./3tier_var.file 

  tasks:
    - os_server:
        cloud: ospcloud
        name: "{{ item.server_del }}"
        state: absent
      with_items: "{{ servers_delete }}"
      register: deleteosp