---
- name: Dynamic inventory from OSP
  hosts: jumpbox
  gather_facts: false

  tasks:
  - name: Fetch Instance Info
    tags: dynamic_inventory
    os_server_facts:
      cloud: ospcloud
      region_name: RegionOne
    register: result


  - name: Add host to metadata group
    tags: dynamic_inventory
    add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.group }}"
    with_items: "{{result.ansible_facts.openstack_servers}}"

  - name: Add host to deployment name group
    tags: dynamic_inventory
    add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.deployment_name }}"
    with_items: "{{result.ansible_facts.openstack_servers}}"